version: "2.2"
services:
  riemann:
    build:
      context: ./riemann
    ports:
      - "5555:5555"
      - "5555:5555/udp"
      - "5556:5556"
  
  riemann-dash:
    build: 
      context: ./riemann-dash
    ports:
      - "4567:4567"
    links:
      - riemann
